### PR TITLE
PR fixes #4577

### LINKED ISSUE #4577: --gui=console does not work in master or devel
See PR #4578.

Mystery solved: `leo some-leo-file --gui=console works in devel, even with Python 3.14.

Here is the log produced by Leo's `listen-to-log` command when executing `leo --gui=console`:
```console
About to start TCP server...
--------------------
trace: load_session Ignoring invalid session unl: 'unl:gnx://C:/Repos/wang/leo/core/LeoPyRef.leo#ekr.20031218072017.2406'
   pr: Can not create workbook
   pr: Traceback (most recent call last):
   pr:   File "C:\Repos\leo-editor\leo\core\leoApp.py", line 2379, in doPostPluginsInit
   pr:     c1 = lm.openWorkBook()
   pr:   File "C:\Repos\leo-editor\leo\core\leoApp.py", line 2430, in openWorkBook
   pr:     c.frame.top.leo_master.setTabName(c, fn)
   pr:     ^^^^^^^^^^^^^^^^^^^^^^
   pr: AttributeError: 'TopFrame' object has no attribute 'leo_master'
listener suspended
```

### PR DESCRIPTION
**Pull request by edreamleo**
See #4577.

- [x] Curate sessions in `SessionManager.get_session`.
- [x] Remove traces to `SessionManager.load_session`.
- [x] Add `self.leo_master = g.NullObject()` to `TopFrame` class to avoid crash.
- [x] Add `windows-curses[curses]; platform_system=="Windows" ; python_version <= "3.14"` to both requirements lists.

### CODE REVIEW

**Comment by edreamleo** [comment]
@boltex This PR is ready for review.

**Review by boltex — COMMENTED** [review]
Looks good. I've not ported it to leojs because i need my get_session method to not be async, and the current code still is functionally somewhat equivalent.

**Comment by edreamleo** [comment]
@boltex Thanks for your review.
