### ISSUE TITLE
--gui=console does not work in master or devel

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#4577]
See PR #4578.

Mystery solved: `leo some-leo-file --gui=console works in devel, even with Python 3.14.

Here is the log produced by Leo's `listen-to-log` command when executing `leo --gui=console`:
```console
About to start TCP server...
--------------------
trace: load_session Ignoring invalid session unl: 'unl:gnx://C:/Repos/wang/leo/core/LeoPyRef.leo#ekr.20031218072017.2406'
   pr: Can not create workbook
   pr: Traceback (most recent call last):
   pr:   File "C:\Repos\leo-editor\leo\core\leoApp.py", line 2379, in doPostPluginsInit
   pr:     c1 = lm.openWorkBook()
   pr:   File "C:\Repos\leo-editor\leo\core\leoApp.py", line 2430, in openWorkBook
   pr:     c.frame.top.leo_master.setTabName(c, fn)
   pr:     ^^^^^^^^^^^^^^^^^^^^^^
   pr: AttributeError: 'TopFrame' object has no attribute 'leo_master'
listener suspended
```
