### ISSUE TITLE
AttributeError: 'LeoFigureManagerQT' object has no attribute '_get_toolbar'

### ISSUE THREAD

**Issue by lmsteffan** [leo-editor/leo-editor#3461]
When I click on a @pyplot node (after having created a viewrender pane) I get the above error.
This happens both in the stable release and in the development (githib) version :

Leo 6.7.4-devel, devel branch, build 74cab839ec
2023-07-23 02:56:28 -0500

**Comment by tbpassin** [comment]
This is most likely because of a change in the MatPlotlib API.  What version of MatPlotlib do you have installed?  A different program of mine won't work with MatPlotlib > 3.6.3.  I need to figure out how to update my program for it one of these days.

**Comment by lmsteffan** [comment]
That's indeed Matplotlib 3.7.2.
Can I do something to make it work ? I am not very familiar with the MatPlotlib API, but I could look it up, I guess.

**Comment by tbpassin** [comment]
You can try to downgrade the version.  I'd try for 3.6.3.  You can always restore your current version later.  If you don't know how, I'd do the following.

1. Close any program (like Leo) that might be using Matplotlib.
2. Check whether MatPlotlib is installed for user or everyone (if you don't know) - on Linux, substitute your command for Python3 for "py":
`py -m pip show matplotlib`
3. If it's located under your home directory, include the `--user` argument, otherwise omit it:
`py -m pip install --upgrade --user matplotlib==3.6.3`
**Note - ** NO space allowed before the "==".
**Note - ** The double equals "==" is not a mistake; it is required.

**Comment by lmsteffan** [comment]
Thanks for your suggestions. I will create a new virtual environment with version 3.6.3 and see how it goes, using your last command, and I'll report the results here.

**Comment by tbpassin** [comment]
BTW, you can find out what versions are available for your Python version and platform by omitting the actual version specification:
`py -m pip install --upgrade --user matplotlib==`

And you can get pip to go through the motions but not actually change anything by using the _--dry-run_ argument:
`py -m pip install --upgrade --user --dry-run matplotlib==3.6.3`

**Comment by lmsteffan** [comment]
I tried with various versions of MatPlotlib. The error appears as early as 3.6.0 ; with previous versions, there was anotrher error.
When I have some  time I'll try to investigate, however it's not a critical bug for me.

**Comment by tbpassin** [comment]
I used to have `@pyplot` nodes working with Viewrendered3.  But I came to dislike them, for several reasons.  One was that the after viewing one, pyplot graphs always went to the plugin's panel even if I didn't want that.  Another was that it was jarring when trying to edit the code for a graph - every time you'd switch back to the node, it would try to plot even if the code were buggy or in development.

Eventually I decided to stop having VR3 support pyplot nodes.  I thought I remembered that we had agreed to have Viewrendered drop the support too.  Either I remember wrongly or it fell through the cracks.  Nowadays, if I want to see pyplot graphs in the VR3 pane I have pyplot write the output to a file and use ReStructuredText/markdown/asciidoc to display it in the VR3 pane.  It's true that this doesn't give you a live toolbar, but you can always go back to pyplotting outside of the VR/VR3 pane.

I actually have prototype code (not part of VR3) that lets pyplot plot into a tab pane in the plot frame, using Qt.  But for some unknown reason, the toolbar is inactive although it is visible.
