### ISSUE TITLE
Leo does not work with PyQt5 version 5.5.0

### ISSUE THREAD

**Issue by alacnorr** [leo-editor/leo-editor#201]
Leo does not start after installing PyQt5 version 5.5.0.
Here is my traceback.

Traceback (most recent call last):
  File "D:\leo-editor\launchLeo.py", line 8, in <module>
    leo.core.runLeo.run()
  File "D:\leo-editor\leo\core\runLeo.py", line 63, in run
    g.app.loadManager.load(fileName, pymacs)
  File "D:\leo-editor\leo\core\leoApp.py", line 2688, in load
    lm.doPrePluginsInit(fileName, pymacs)
  File "D:\leo-editor\leo\core\leoApp.py", line 2754, in doPrePluginsInit
    lm.createGui(pymacs)
  File "D:\leo-editor\leo\core\leoApp.py", line 2779, in createGui
    lm.createSpecialGui(gui_option, pymacs, script, windowFlag)
  File "D:\leo-editor\leo\core\leoApp.py", line 2794, in createSpecialGui
    g.app.createDefaultGui()
  File "D:\leo-editor\leo\core\leoApp.py", line 1738, in createDefaultGui
    app.createQtGui(fileName, verbose=verbose)
  File "D:\leo-editor\leo\core\leoApp.py", line 1758, in createQtGui
    import leo.plugins.qt_gui as qt_gui
  File "D:\leo-editor\leo\plugins\qt_gui.py", line 12, in <module>
    import leo.plugins.qt_big_text as qt_big_text
  File "D:\leo-editor\leo\plugins\qt_big_text.py", line 6, in <module>
    import leo.plugins.qt_text as qt_text
  File "D:\leo-editor\leo\plugins\qt_text.py", line 434, in <module>
    class LeoLineTextWidget(QtWidgets.QFrame):
AttributeError: 'NoneType' object has no attribute 'QFrame'

**Comment by edreamleo** [comment]
Thanks for this report.  What version of Windows are you using?

**Comment by alacnorr** [comment]
At the time of reporting I was using Windows 8.1 x64. I am having the same issue now with Windows 10 x64. I use x64 versions of python and PyQt5. If I launch Leo from another python installation in the same machine (same python version 3.4.3 x64) but with PyQt4 x64, it works fine. Thanks in advance for your help.

**Comment by edreamleo** [comment]
It works for me with Python 3.4.2, PyQt version 5.5.1 on a 64-bit Windows 10 system but with **32-bit** versions of Python and PyQt. I probabably installed 32-bit Python because at the time there was no matching 64-bit version of PyQt.

Just now I uninstalled a previous version of PyQt and installed PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x32.exe, downloaded from https://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.5.1/

**Next**: I'll test with 64-bit Python and PyQt and report.

**Comment by edreamleo** [comment]
I have just installed the 64-bit versions of Python 3.4 and PyQt5.5.1 on Windows 10 from the following files:

- python-3.4.4.amd64.msi
- PyQt5-5.5.1-gpl-Py3.4-Qt5.5.1-x64.exe

The install works fine, afaik. I am going to close this issue.

**Comment by edreamleo** [comment]
I am going to reopen this.  Lots of unit tests fail, with the following message:

Data set on unsupported clipboard mode. QMimeData object will be deleted.

Googling this brings up a previous Leo discussion.

**Comment by edreamleo** [comment]
Leo mostly works correctly with the Anaconda distro. I am going to close this particular issue. There are indeed issues with the clipboard, and with hard crashes during shutdown, but this issue is misnamed.
