### ISSUE TITLE
Python importer fails for python 3.6

### ISSUE THREAD

**Issue by edreamleo** [leo-editor/leo-editor#2377]
```
 File "c:\leo.repo\leo-editor\leo\plugins\importers\python.py", line 163, in getdefn
    if t[0] in (token.DEDENT, token.COMMENT):
AttributeError: module 'token' has no attribute 'COMMENT'
```

**Comment by vitalije** [comment]
The obvious solution would be to require Python 3.7

**Comment by edreamleo** [comment]
@vitalije Imo, the python importer should continue to work with Python 3.6. Do you think that is possible?

**Comment by vitalije** [comment]
That would require substantial work. The `tokenize` module would be useless in this case and practically it have to be re-implemented in python. Why do you think that it is important to support Python3.6? That is 3 versions behind the current stable python version. Python3.6 isn't anymore on the list of active Python branches. Look [here](https://devguide.python.org/#status-of-python-branches). Python3.7 is the last.

I believe it would be counter productive to rewrite python importer now to support Python3.6 when it is already dropped by the official Python developers.

Look at the official python documentation for [the version 3.6](https://docs.python.org/3.6/library/index.html). It has a red banner on the top with the warning that it isn't supported anymore and the upgrade is recommended.

**Comment by edreamleo** [comment]
Fixed in devel by failing (with a message) for python 3.6. Adjusted unit tests accordingly.
