### ISSUE TITLE
mindmap AttributeError: 'QFontMetrics'

### ISSUE THREAD

**Issue by LewisNeal** [leo-editor/leo-editor#3014]
I get errors running mmap-list or mmap-tree commands.
Only occurs on Python 3.11,  mmap works fine on Python 3.10.8 PC.

_Leo Log Window
Leo 6.7.2-devel, devel branch, build b3e28a9800
2022-12-26 15:55:43 -0800
Python 3.11.0, PyQt version 6.4.1
Windows 10 AMD64 (build 10.0.19044) SP0
read 6 files in 0.32 seconds
read outline in 0.44 seconds
exception executing script
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 784, in executeScript
c.executeScriptHelper(args, define_g, define_name, namespace, script)
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 823, in executeScriptHelper
exec(compile(script, scriptFile, 'exec'), d)
  File "C:/Users/lewis/.leo/scriptFile.py", line 38, in <module>
SVG_HEADER = f'''<?xml version="1.0" encoding="utf-8"?>
^^^^^^^^^^^^^^^^^^
  File "C:/Users/lewis/.leo/scriptFile.py", line 762, in build_mmap
svg = create_map(IndentedParser, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/Users/lewis/.leo/scriptFile.py", line 407, in create_map
blocks = create_blocks(root)
^^^^^^^^^^^^^^^^^^^
  File "C:/Users/lewis/.leo/scriptFile.py", line 450, in create_blocks
item.width = FONT_RESCALE * FM.width(label)
^^^^^^^^
AttributeError: 'QFontMetrics' object has no attribute 'width'
is_sentinel: can not happen. delims: (None, '')
is_sentinel: can not happen. delims: (None, '')
is_sentinel: can not happen. delims: (None, '')
is_sentinel: can not happen. delims: (None, '')
only 4 lines
--------------------
  line 449: item = Item(label)
* line 450: item.width = FONT_RESCALE * FM.width(label)
  line 451: items.append(item)
  line 452:
[end]_

**Comment by tbpassin** [comment]
Thanks for the report.  I don't have Python 3.11 installed.  I suppose I will have to bite the bullet at last.  It sounds like either Tk has changed the API with 3.11 or there's a bug in tkinter as compiled for 3.11.  I'll see what I can unearth.

Glad to know that someone else is using the scripts!

**Comment by tbpassin** [comment]
Turns out the width attribute is deprecated.  I found this:

"[QFontMetrics.width()](https://doc.qt.io/qt-5/qfontmetrics-obsolete.html#width) has been considered obsolete since Qt 5.5 and deprecated from Qt 5.11 (but will probably be still supported throughout any future releases of Qt 5), and eventually removed in Qt 6.

As the documentation (which already is in the obsolete members page of Qt5) reports, the results of width() were inconsistent and unreliable in many situations, mostly because it didn't consider the letter bearings.

You should use [horizontalAdvance()](https://doc.qt.io/qt-5/qfontmetrics.html#horizontalAdvance) or [boundingRect()](https://doc.qt.io/qt-5/qfontmetrics.html#boundingRect).width()."

(from https://stackoverflow.com/questions/65992699/qfontmetrics-width-using-pyside6).

So go into the script and change `width` to `horizontalAdvance` and see if that works.  Ill make the same change too.

**Comment by tbpassin** [comment]
Looks like I made that change some time ago.  My own code does contain 

```
label_width = FONT_RESCALE * FM.horizontalAdvance(label)
```

There are several other places to change from `width()` to `horizontalAdvance()`, too.  A search should find them all.

**Comment by tbpassin** [comment]
I checked the version in _scripts.leo_, and it already uses `horizontalAdvance()`.

**Comment by tbpassin** [comment]
@LewisNeal, can we close this issue now?

**Comment by LewisNeal** [comment]
@tbpassin mmap is a very useful script. Thanks for your work.

Using leo I updated the scripts.leo file.
Before running mmap-tree command I deleted scriptFile.py from my .leo directory.
Here are errors running mmap-tree command:

Leo Log Window
Leo 6.7.2-devel, devel branch, build f1b522eb79
2022-12-29 12:52:34 -0600
Python 3.11.0, PyQt version 6.4.1
Windows 10 AMD64 (build 10.0.19044) SP0
read outline in 0.07 seconds
exception executing script
Traceback (most recent call last):
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 784, in executeScript
c.executeScriptHelper(args, define_g, define_name, namespace, script)
  File "N:\git\leo-editor\leo\core\leoCommands.py", line 823, in executeScriptHelper
exec(compile(script, scriptFile, 'exec'), d)
  File "C:/Users/lewis/.leo/scriptFile.py", line 38, in <module>
SVG_HEADER = f'''<?xml version="1.0" encoding="utf-8"?>

  File "C:/Users/lewis/.leo/scriptFile.py", line 762, in build_mmap
svg = create_map(IndentedParser, data)

  File "C:/Users/lewis/.leo/scriptFile.py", line 412, in create_map
first_level = layout_am_1st_level(root, left, axes)

  File "C:/Users/lewis/.leo/scriptFile.py", line 493, in layout_am_1st_level
label_width, _ = get_longest_label(root.children)

  File "C:/Users/lewis/.leo/scriptFile.py", line 305, in get_longest_label
label_len = FM.width(longest_label) + xpadding

AttributeError: 'QFontMetrics' object has no attribute 'width'
only 0 lines

  line 304:
* line 305: label_len = FM.width(longest_label) + xpadding
  line 306:
  line 307: return label_len, longest_label

**Comment by tbpassin** [comment]
It's a little strange.  My checkout of the devel branch is 91b2c6c2cc8a942f36bef163ec0bea14d0a5bea7.  In it, `FM.width` has been replaced with `FM.horizontalAdvance`.  The mmap-tree works as expected.  

I do not know why your checkout has a different commit hash, but I think the change to horizontalAdvance was not made recently.  The first commit that included the mmap-* scripts was about a year ago, at commit 6122371ee6d64f062377444385fafb27dfcaf906.  At that time it already used `FM.horizontalAdvance`.

Anyway, please make sure you have the current commit, 91b2c6c2cc8a942f36bef163ec0bea14d0a5bea7.  Or you can do a search-and-replace to replace FM.width with FM.horizontalAdvance in several places.  Then the script will work.

Could you possibly have copied an old version of the scripts into your local settings file or even the outline you are working with?  That could possibly explain how you get an old version even with a newer commit.

**Comment by LewisNeal** [comment]
I updated an old version of the scripts in my local settings. The script works and thanks for that prompt.

**Comment by tbpassin** [comment]
I'm so glad!  It was a luck guess.
