### ISSUE TITLE
Cannot open any entries under File->Recent Files

### ISSUE THREAD

**Issue by gatesphere** [leo-editor/leo-editor#4784]
Win 10 Python 3.10 devel commit 18e1d26b90

Opening anything in recent files nets this error:
```
<redacted>python.exe <redacted>\leo-editor\launchLeo.py
Leo 6.8.10-devel, devel branch, build 18e1d26b90
2026-07-08 09:56:14 -0500
Python 3.10.6, PyQt version 6.6.3
Windows 10 AMD64 (build 10.0.19045) SP0

Uncaught exception in Leo...
Traceback (most recent call last):
  File "<redacted>repos\leo-editor\leo\plugins\qt_frame.py", line 2759, in qt
_add_command_callback
    return command()
TypeError: RecentFilesManager.createRecentFilesMenuItems.<locals>.recentFilesCal
lback() missing 1 required positional argument: 'event'
```

**Comment by gatesphere** [comment]
git bisect points to problem commit 528cdbd1e4dd4d0e647e5cac6ed49883e9a8f8f3

**Comment by edreamleo** [comment]
On Wed, Jul 8, 2026 at 7:34 PM Jacob Peck ***@***.***> wrote:

> *gatesphere* left a comment (leo-editor/leo-editor#4784)
> <https://github.com/leo-editor/leo-editor/issues/4784#issuecomment-4920418910>
>
> git bisect points to problem commit 528cdbd
> <https://github.com/leo-editor/leo-editor/commit/528cdbd1e4dd4d0e647e5cac6ed49883e9a8f8f3>
>
Thanks for this research!

The root of this issue was a brain spike on my part, which I noticed
yesterday while working on PR #4783
<https://github.com/leo-editor/leo-editor/pull/4783>. I'll merge this PR in
a few hours.

Edward

**Comment by edreamleo** [comment]
@gatesphere Please reopen if necessary.

**Comment by gatesphere** [comment]
> [@gatesphere](https://github.com/gatesphere) Please reopen if necessary.

Appears fixed after pull of recent work.  Thanks!

**Comment by edreamleo** [comment]
@gatesphere Thanks, Jake, for the confirmation.
