### ISSUE TITLE
richtext plugin does not work with Python 3.4.3 & PyQt 5.2.1

### ISSUE THREAD

**Issue by SegundoBob** [leo-editor/leo-editor#222]
When I move focus to a @rich node, I get this error:
```
hook failed: select3, <function at_rich_check at 0x7f746aa640d0>, leo.plugins.richtext
Traceback (most recent call last):
  File "/pri/git/leo-editor/leo/core/leoPlugins.py", line 322, in callTagHandler
    result = handler(tag, keywords)
  File "/pri/git/leo-editor/leo/plugins/richtext.py", line 286, in at_rich_check
    cmd_OpenEditor(key, at_rich=True)
  File "/pri/git/leo-editor/leo/plugins/richtext.py", line 300, in cmd_OpenEditor
    w = CKEEditor(c=c)
  File "/pri/git/leo-editor/leo/plugins/richtext.py", line 133, in __init__
    QtWebKit.QWebSettings.globalSettings().setAttribute(
AttributeError: 'NoneType' object has no attribute 'QWebSettings'
```
Test System
---------------
```
build 20150924110144, Thu Sep 24 11:01:44 CDT 2015
```
and
```
build 20151122092056, Sun Nov 22 09:20:56 CST 2015
```

Xubuntu64 14.04
Python 3.4.3, PyQt version 5.2.1

The richtext plugin works with

Xubuntu64 14.04
Python 2.7.6, PyQt version 4.8.6

**Comment by SegundoBob** [comment]
This was my mistake.  I did not have Ubuntu package python3-pyqt5.qtwebkit installed.  Once I installed this package, the richtext plugin worked fine with Python 3.
